### ISSUE TITLE
Move this repo into W3C space?

### ISSUE THREAD

**Issue by xfq** [w3c/screen-fold#36]
First, thank you for working on this!

Since it's in the [draft Devices and Sensors Working Group Charter](https://w3c.github.io/dap-charter/DASCharter-2020.html#deliverables), I think we can move the repo to W3C space (I can help with that) and work on it as an editor's draft of the Devices and Sensors Working Group. After the new charter is approved, we can publish a First Public Working Draft.

/cc @anssiko @reillyeon

**Comment by kenchris** [comment]
Sounds good to me @anssiko

**Comment by diekus** [comment]
Great news! It's currently in my github, let me know if I can help transfer it.

**Comment by xfq** [comment]
Thank you @diekus! Could you give me admin or owner permissions for this repo?

**Comment by diekus** [comment]
@xfq on it!

**Comment by xfq** [comment]
It does not seem to work indeed. Can you transfer the repo to me (temporarily)? I will transfer it to W3C, and give you access.

**Comment by xfq** [comment]
Done. Thank you @diekus!
